development:
  api_sources: 
    - '../rhodes/lib/commonAPI/'
    - '../Motorola-Extensions/lib/commonAPI/'
    - '../rhodes/res/generators/templates/api/xml_templates/'
    - '../rhoconnect-client/ext/rhoconnect-client/ext/'
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  guides_eb: 'eb/en/edge/guide/'
  launchpad_eb: 'eb/en/edge/export/launchpad/'
  launchpad_eb_mapping: 'index.hash'
  offline_eb: 'eb/en/edge/export/offline/'
  offline_eb_mapping: 'eb/en/edge/export/offline/offlineDocs/docs/docs.js'

  index: 'rhodocs'
  pdfkithost: 'localhost:9393'
  current_version: '5.5'
jenkins:
  api_sources: 
    - '../../rhodes/workspace/lib/commonAPI/'
    - '../../Motorola-Extensions/workspace/lib/commonAPI/'
    - '../../rhodes/workspace/res/generators/templates/api/xml_templates/'
    - '../../rhoconnect-client/workspace/ext/rhoconnect-client/ext/'
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  guides_eb: 'eb/en/edge/guide/'
  launchpad_eb: 'eb/en/edge/export/launchpad/'
  launchpad_eb_mapping: 'index.hash'
  offline_eb: 'eb/en/edge/export/offline/'
  offline_eb_mapping: 'index.json'
  index: 'rhodocs'
  pdfkithost: 'localhost:9393'
  current_version: '5.5'
edge:
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  guides_eb: 'eb/en/edge/guide/'
  launchpad_eb: 'eb/en/edge/export/launchpad/'
  launchpad_eb_mapping: 'index.hash'
  offline_eb: 'eb/en/edge/export/offline/'
  offline_eb_mapping: 'index.json'
  index: 'rhodocs'
  pdfkithost: 'edgedocs.rhomobile.com'
  current_version: '5.5'
production:
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  guides_eb: 'eb/en/edge/guide/'
  launchpad_eb: 'eb/en/edge/export/launchpad/'
  launchpad_eb_mapping: 'index.hash'
  offline_eb: 'eb/en/edge/export/offline/'
  offline_eb_mapping: 'index.json'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'
  current_version: '5.5'
